# Generated by Django 5.0.2 on 2025-10-08 09:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0003_initial'),
        ('services', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConciergeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('request_number', models.CharField(editable=False, help_text='Format: CR-YYYY-NNNNNN', max_length=20, unique=True)),
                ('request_type', models.CharField(choices=[('alcohol', 'Premium Alcohol 🥃'), ('flowers', 'Fresh Flowers 🌹'), ('food', 'Gourmet Food 🍽️'), ('jewelry', 'Jewelry & Accessories 💎'), ('luxury', 'Luxury Items ✨'), ('gift', 'Gift Items 🎁'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(help_text='Brief title of request', max_length=200)),
                ('description', models.TextField(help_text='Detailed description')),
                ('product_link', models.URLField(blank=True, help_text='Optional product link')),
                ('budget_min', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('budget_max', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('preferred_pickup_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('processing', 'Processing'), ('ready', 'Ready for Pickup'), ('completed', 'Completed'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal staff notes')),
                ('decline_reason', models.TextField(blank=True)),
                ('requires_age_verification', models.BooleanField(default=False, help_text='For alcohol purchases')),
                ('age_verified', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('quickbooks_synced', models.BooleanField(default=False)),
                ('quickbooks_invoice_id', models.CharField(blank=True, max_length=100)),
                ('quickbooks_sync_error', models.TextField(blank=True)),
                ('attachments', models.JSONField(blank=True, default=list, help_text='Reference images or links')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concierge_requests', to='payments.payment')),
                ('pickup_booking', models.ForeignKey(blank=True, help_text='Link to booking for pickup', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concierge_requests', to='services.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concierge_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Concierge Request',
                'verbose_name_plural': 'Concierge Requests',
                'db_table': 'concierge_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='concierge_r_user_id_3075ca_idx'), models.Index(fields=['status', 'preferred_pickup_date'], name='concierge_r_status_79c96c_idx')],
            },
        ),
    ]
