# Generated by Django 5.0.2 on 2025-10-29 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True, help_text='Receive email notifications')),
                ('email_booking_confirmations', models.BooleanField(default=True)),
                ('email_reminders', models.BooleanField(default=True)),
                ('email_review_requests', models.BooleanField(default=True)),
                ('email_marketing', models.BooleanField(default=False)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('sms_phone', models.CharField(blank=True, max_length=20)),
                ('push_enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254)),
                ('recipient_name', models.CharField(blank=True, max_length=255)),
                ('email_type', models.CharField(choices=[('booking_confirmation', 'Booking Confirmation'), ('booking_reminder', '24hr Reminder'), ('review_request', 'Review Request'), ('membership_welcome', 'Membership Welcome'), ('password_reset', 'Password Reset'), ('payment_receipt', 'Payment Receipt'), ('cancellation', 'Booking Cancellation')], max_length=30)),
                ('subject', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('bounced', 'Bounced')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('sendgrid_message_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='services.booking')),
            ],
            options={
                'verbose_name': 'Email Log',
                'verbose_name_plural': 'Email Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='notificatio_created_4c6dec_idx'), models.Index(fields=['status', '-created_at'], name='notificatio_status_d84ea4_idx'), models.Index(fields=['email_type', '-created_at'], name='notificatio_email_t_e9837a_idx'), models.Index(fields=['booking', '-created_at'], name='notificatio_booking_f5aa69_idx')],
            },
        ),
    ]
