# Generated by Django 5.0.2 on 2025-10-29 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='email_type',
            field=models.CharField(choices=[('booking_confirmation', 'Booking Confirmation'), ('booking_reminder', '24hr Reminder'), ('review_request', 'Review Request'), ('membership_welcome', 'Membership Welcome'), ('technician_notification', 'Technician Notification'), ('password_reset', 'Password Reset'), ('payment_receipt', 'Payment Receipt'), ('cancellation', 'Booking Cancellation')], max_length=30),
        ),
    ]
