# Generated by Django 5.0.2 on 2025-10-08 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuporder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.pickuporder'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_active'], name='shop_produc_categor_cc0807_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_featured', 'is_active'], name='shop_produc_is_feat_67fd6c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='shop_produc_slug_e8afd2_idx'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='shop.product'),
        ),
        migrations.AddIndex(
            model_name='pickuporder',
            index=models.Index(fields=['user', 'status'], name='pickup_orde_user_id_3f69d0_idx'),
        ),
        migrations.AddIndex(
            model_name='pickuporder',
            index=models.Index(fields=['status', 'pickup_date'], name='pickup_orde_status_1c1e12_idx'),
        ),
        migrations.AddIndex(
            model_name='pickuporder',
            index=models.Index(fields=['order_number'], name='pickup_orde_order_n_3460ba_idx'),
        ),
    ]
