# Generated by Django 5.0.2 on 2025-09-25 10:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('services_used_this_month', models.PositiveIntegerField(default=0)),
                ('guest_passes_used', models.PositiveIntegerField(default=0)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=100)),
                ('auto_renew', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Membership',
                'verbose_name_plural': 'Memberships',
                'db_table': 'memberships',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='MembershipBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('benefit_type', models.CharField(choices=[('discount', 'Discount'), ('access', 'Special Access'), ('service', 'Free Service'), ('amenity', 'Amenity'), ('priority', 'Priority')], max_length=20)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('value', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Membership Benefit',
                'verbose_name_plural': 'Membership Benefits',
                'db_table': 'membership_benefits',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('short_description', models.CharField(blank=True, max_length=300)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('duration_months', models.PositiveIntegerField(choices=[(1, '1 Month'), (3, '3 Months'), (6, '6 Months'), (12, '12 Months'), (24, '24 Months')])),
                ('benefits', models.JSONField(default=list, help_text='List of membership benefits')),
                ('discount_percentage', models.PositiveIntegerField(default=0, help_text='Discount percentage on services', validators=[django.core.validators.MaxValueValidator(100)])),
                ('mensuite_access', models.BooleanField(default=True)),
                ('coresync_private_access', models.BooleanField(default=True)),
                ('iot_control_access', models.BooleanField(default=True)),
                ('priority_booking', models.BooleanField(default=False)),
                ('monthly_service_credits', models.PositiveIntegerField(default=0, help_text='Number of free services per month (0 = unlimited)')),
                ('guest_passes', models.PositiveIntegerField(default=0, help_text='Number of guest passes included')),
                ('featured', models.BooleanField(default=False)),
                ('color_scheme', models.CharField(default='#000000', max_length=7)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Membership Plan',
                'verbose_name_plural': 'Membership Plans',
                'db_table': 'membership_plans',
                'ordering': ['order', 'price'],
            },
        ),
    ]
