# Generated by Django 5.0.2 on 2025-10-29 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_initial'),
        ('technicians', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='ai_session_id',
            field=models.CharField(blank=True, help_text='AI conversation session ID (trace conversation)', max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='atlas_call_id',
            field=models.CharField(blank=True, help_text='Atlas AI phone booking call ID (trace)', max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='google_calendar_event_id',
            field=models.CharField(blank=True, help_text='Google Calendar event ID (sync reference)', max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='technician',
            field=models.ForeignKey(blank=True, help_text='Assigned technician (new portal integration)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='technicians.technician'),
        ),
    ]
