# Generated by Django 5.0.2 on 2025-10-29 19:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_booking_ai_session_id_booking_atlas_call_id_and_more'),
        ('technicians', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['technician', 'booking_date'], name='bookings_technic_883f03_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['technician', 'status', 'booking_date'], name='bookings_technic_eae844_idx'),
        ),
    ]
