# Generated by Django 5.0.2 on 2025-09-25 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iot_control', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='controllog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='control_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controllog',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_logs', to='iot_control.iotdevice'),
        ),
        migrations.AddField(
            model_name='scene',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Leave blank for preset scenes', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controllog',
            name='scene',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='control_logs', to='iot_control.scene'),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_readings', to='iot_control.iotdevice'),
        ),
        migrations.AddIndex(
            model_name='sensorreading',
            index=models.Index(fields=['device', 'reading_type', '-timestamp'], name='sensor_read_device__6e803b_idx'),
        ),
    ]
